model:
  weights_path: "models/best2.onnx"
  tracker_config: "botsort.yaml"
  confidence: 0.5
roi:
  # Polygon points calibrated from ROICalibration.py
  polygon: [[626, 439], [9, 429], [188, 7], [462, 2], [633, 435]]
  finish_line_y: 350


filters:
  min_box_area: 5
  min_lifespan_sec: 0
shifts:
  - name: "Morning_Shift"
    start_hour: 6
    end_hour: 14
  - name: "Evening_Shift"
    start_hour: 14
    end_hour: 22
  - name: "Night_Shift"
    start_hour: 22
    end_hour: 6
