model:
  weights_path: "models/best2.onnx"
  tracker_config: "botsort.yaml"
  confidence: 0.6
roi:
  # Polygon points calibrated from ROICalibration.py
  polygon: [[728, 124], [252, 1024], [1680, 1045], [1300, 153], [722, 124]]
  finish_line_y: 600

filters:
  min_box_area: 5
  min_lifespan_sec: 0
shifts:
  - name: "Morning_Shift"
    start_hour: 6
    end_hour: 14
  - name: "Evening_Shift"
    start_hour: 14
    end_hour: 22
  - name: "Night_Shift"
    start_hour: 22
    end_hour: 6