listener 1883
protocol mqtt

listener 8883
protocol mqtt

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

password_file /mosquitto/config/passwd
allow_anonymous false
